"use client";

import React from "react";
import Image from "next/image";
import AnimatedText from "@/components/AnimatedText";
import CountUp from "@/components/CountUp";
import Link from "next/link";
import { useHomeViewModel } from "./useHomeViewModel";
import { whyChooseUsPoints, type WhyChooseUsIconId } from "./HomeModel";
import BecomeATutorModal from "../../components/BecomeATutorModal";
import "./HomeView.css";

const WhyIcon: React.FC<{ id: WhyChooseUsIconId }> = ({ id }) => {
  const common = { xmlns: "http://www.w3.org/2000/svg", viewBox: "0 0 24 24", width: 24, height: 24, fill: "none", stroke: "currentColor", strokeWidth: 1.8, strokeLinecap: "round" as const, strokeLinejoin: "round" as const, "aria-hidden": true, focusable: false };
  if (id === "shield") return <svg {...common}><path d="M12 3l8 3v5c0 5-3.5 8.5-8 10-4.5-1.5-8-5-8-10V6l8-3z" /><path d="M9 12l2 2 4-4" /></svg>;
  if (id === "spark") return <svg {...common}><path d="M12 3v3M12 18v3M3 12h3M18 12h3M5.6 5.6l2.1 2.1M16.3 16.3l2.1 2.1M5.6 18.4l2.1-2.1M16.3 7.7l2.1-2.1" /></svg>;
  if (id === "clock") return <svg {...common}><circle cx="12" cy="12" r="9" /><path d="M12 7v5l3 2" /></svg>;
  return <svg {...common}><circle cx="12" cy="12" r="9" /><path d="M3 12h18M12 3c2.8 3 2.8 15 0 18M12 3c-2.8 3-2.8 15 0 18" /></svg>;
};
const StarIcon: React.FC<{ filled: boolean }> = ({ filled }) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="16" height="16" fill={filled ? "currentColor" : "none"} stroke="currentColor" strokeWidth="1.6" aria-hidden="true"><path d="M12 2.5l2.95 6 6.6.95-4.78 4.66 1.13 6.58L12 17.6l-5.9 3.1 1.13-6.58L2.45 9.45l6.6-.95L12 2.5z" /></svg>;
const ChevronIcon: React.FC<{ open: boolean }> = ({ open }) => <svg className={`faq__chevron${open ? " faq__chevron--open" : ""}`} xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><path d="M6 9l6 6 6-6" /></svg>;
const ContactInfoIcon: React.FC<{ kind: "mail" | "clock" | "pin" }> = ({ kind }) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{kind === "mail" ? <><rect x="3" y="5" width="18" height="14" rx="2" /><path d="M3 7l9 6 9-6" /></> : kind === "clock" ? <><circle cx="12" cy="12" r="9" /><path d="M12 7v5l3 2" /></> : <><path d="M12 22s7-7.2 7-12a7 7 0 1 0-14 0c0 4.8 7 12 7 12z" /><circle cx="12" cy="10" r="2.5" /></>}</svg>;

export default function HomeView() {
  const vm = useHomeViewModel();
  const [tutorModalOpen, setTutorModalOpen] = React.useState(false);
  const { testimonials, currentTestimonialIndex, nextTestimonial, previousTestimonial, goToTestimonial } = vm;
  const testimonialSlides = [...testimonials, ...testimonials];

  React.useEffect(() => {
    const sections = Array.from(document.querySelectorAll<HTMLElement>(".home-view > section"));
    if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) sections.forEach((section) => section.classList.add("is-visible"));
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) { entry.target.classList.add("is-visible"); observer.unobserve(entry.target); } }), { threshold: 0.12 });
    sections.forEach((section) => observer.observe(section));
    return () => observer.disconnect();
  }, []);

  return <div className="home-view">
    <section id="hero" className="hero" aria-labelledby="hero-heading"><div className="hero__inner"><div className="hero__content"><p className="eyebrow">1-ON-1 LEARNING THAT WORKS</p><h1 id="hero-heading" className="hero__heading"><AnimatedText text="The right tutor for every learner — at any age, any level." /></h1><p className="hero__subtext">TutorFinder connects students of all ages with vetted tutors who fit how they learn. Find yours in minutes, not weeks.</p><div className="hero__ctas"><Link href="/search-tutors" className="hero__cta hero__cta--primary">Find a Tutor <span>→</span></Link><button type="button" className="hero__cta hero__cta--outline" onClick={() => setTutorModalOpen(true)}>Become a Tutor</button></div></div><div className="hero__media"><svg className="hero__shape" viewBox="0 0 400 400" aria-hidden="true"><circle cx="200" cy="200" r="180" /></svg><Image src="/images/hero-tutor.jpg" alt="Tutor guiding a learner with digital study tools" width={900} height={760} priority className="hero__image" /><div className="hero__stat-chip"><strong>1,200+</strong><span>vetted tutors</span></div></div></div><a href="#about-us" className="hero__scroll-cue" aria-label="Scroll to About Us"><span className="hero__scroll-cue-arrow" /></a></section>

    <section id="about-us" className="about" aria-labelledby="about-heading"><div className="about__inner"><div className="about__copy"><p className="eyebrow">ABOUT US</p><h2 id="about-heading" className="section-heading"><AnimatedText text="Learning feels better when it fits " /><AnimatedText text="you." className="animated-text--accent" /></h2><p className="about__body">TutorFinder is a marketplace for one-on-one learning. We connect students of any age — from first readers to adult learners picking up a new language — with vetted tutors who match the way they want to learn. Browse by subject, level, and price; book a single session or set a recurring rhythm; learn on your schedule.</p><div className="about__stats" aria-label="Quick stats"><span><strong><CountUp value={1200} suffix="+" /></strong><small>vetted tutors</small></span><span><strong><CountUp value={40} suffix="+" /></strong><small>subjects</small></span><span><strong>Any age,<br />any level</strong><small>one marketplace</small></span></div><a href="#" className="text-link">Learn More About Us <span>→</span></a></div><div className="about__visual"><div className="about__blob" aria-hidden="true" /><Image src="/images/about-tutor.jpg" alt="Tutor and learner sharing a focused study session" width={640} height={720} className="about__image" /><div className="mission-card"><span className="mission-card__icon">✦</span><div><strong>Our Mission</strong><p>Make finding the right learning rhythm feel simple.</p></div></div></div></div></section>

    <section id="why-choose-us" className="why" aria-labelledby="why-heading"><div className="why__inner"><div className="section-intro"><p className="eyebrow">WHY CHOOSE US</p><h2 id="why-heading" className="section-heading"><AnimatedText text="Learning that fits " /><AnimatedText text="you best." className="animated-text--accent" /></h2><p>From first lessons to big milestones, TutorFinder helps learners find support that lasts.</p></div><ul className="why__grid">{whyChooseUsPoints.map((point, index) => <li key={point.title} className={`why__card why__card--${index}`}><span className="why__icon"><WhyIcon id={point.icon} /></span><h3>{point.title}</h3><p>{point.description}</p></li>)}</ul><Link href="/search-tutors" className="why__cta">Find Your Tutor Now <span>→</span></Link></div></section>

    <section id="testimonials" className="testimonials" aria-labelledby="testimonials-heading"><div className="testimonials__inner"><div className="section-intro"><p className="eyebrow">WHAT STUDENTS SAY</p><h2 id="testimonials-heading" className="section-heading"><AnimatedText text="Trusted by students." /><br /><AnimatedText text="Proven by results." className="animated-text--accent" /></h2></div><div className="testimonials__viewport"><ul className="testimonials__track">{testimonialSlides.map((t, index) => <li key={`${t.name}-${index}`} className={`testimonial testimonial--${index % testimonials.length}`}><span className="testimonial__quote-mark">“</span><blockquote>{t.quote}</blockquote><div className="testimonial__stars" aria-label={`Rated ${t.rating} out of 5`}>{[1, 2, 3, 4, 5].map((i) => <StarIcon key={i} filled={i <= t.rating} />)}</div><div className="testimonial__person"><Image src="/images/hero-tutor.jpg" alt={`${t.name} profile`} width={48} height={48} className="testimonial__avatar" /><div><p className="testimonial__name">{t.name}</p><p className="testimonial__role">{t.role}</p></div></div></li>)}</ul></div><div className="testimonials__controls"><button type="button" onClick={previousTestimonial} aria-label="Previous testimonial">←</button><div className="testimonial-dots">{testimonials.map((t, i) => <button key={t.name} type="button" className={i === currentTestimonialIndex ? "is-active" : ""} onClick={() => goToTestimonial(i)} aria-label={`Show testimonial ${i + 1}`} />)}</div><button type="button" onClick={nextTestimonial} aria-label="Next testimonial">→</button></div></div></section>

    <section className="support" aria-label="Frequently asked questions and contact"><div id="faq" className="faq" aria-labelledby="faq-heading"><p className="eyebrow">FAQ</p><h2 id="faq-heading" className="section-heading">Frequently asked<br /><em>questions.</em></h2><ul className="faq__list">{vm.faqItems.map((item, index) => { const open = vm.openFaqIndex === index; return <li key={item.question} className="faq__item"><button type="button" className="faq__question" aria-expanded={open} aria-controls={`faq-panel-${index}`} onClick={() => vm.toggleFaq(index)}><span>{item.question}</span><ChevronIcon open={open} /></button><div id={`faq-panel-${index}`} role="region" className={`faq__answer-wrap${open ? " faq__answer-wrap--open" : ""}`}><p>{item.answer}</p></div></li>; })}</ul></div><div id="contact" className="contact" aria-labelledby="contact-heading"><p className="eyebrow">CONTACT</p><h2 id="contact-heading" className="section-heading">Let&apos;s get in <em>touch.</em></h2><p className="contact__intro">Questions, feedback, or partnership ideas? Send us a note and we&apos;ll get back within two business days.</p><form className="contact__form" onSubmit={vm.handleContactSubmit} noValidate><label>Name<input type="text" value={vm.name} onChange={(e) => vm.setName(e.target.value)} placeholder="Your full name" required disabled={vm.submitting} /></label><label>Email<input type="email" value={vm.email} onChange={(e) => vm.setEmail(e.target.value)} placeholder="you@example.com" required disabled={vm.submitting} /></label><label>Message<textarea value={vm.message} onChange={(e) => vm.setMessage(e.target.value)} placeholder="What can we help with?" rows={4} required disabled={vm.submitting} /></label><button className="contact__submit" type="submit" disabled={vm.submitting}>{vm.submitting ? "Sending…" : "Send Message →"}</button>{vm.success && <p className="contact__success" role="status">Thanks — your message is on its way.</p>}{vm.error && <p className="contact__error" role="alert">{vm.error}</p>}</form><dl className="contact__info-list"><div><dt><ContactInfoIcon kind="mail" />Email</dt><dd><a href="mailto:hello@tutorfinder.example">hello@tutorfinder.example</a></dd></div><div><dt><ContactInfoIcon kind="clock" />Support hours</dt><dd>Monday – Friday, 9:00 – 18:00 (UTC)</dd></div><div><dt><ContactInfoIcon kind="pin" />Based in</dt><dd>Remote, serving learners worldwide</dd></div></dl></div></section>
    <BecomeATutorModal open={tutorModalOpen} onClose={() => setTutorModalOpen(false)} />
  </div>;
}
