"use client";
import Link from "next/link";
import { useEffect, useState, type ReactNode } from "react";
import { usePathname, useRouter } from "next/navigation";
import { useAuth } from "@/context/AuthContext";
import "@/app/dashboard/dashboard.css";

const items = [["/dashboard", "Overview", "grid"], ["/dashboard/profile", "Profile", "user"], ["/dashboard/bookings", "Bookings", "calendar"], ["/messages", "Messages", "message"], ["/dashboard/reviews", "Reviews", "star"], ["/dashboard/earnings", "Earnings", "chart"]] as const;
const pathData: Record<string, string> = { grid: "M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM14 14h6v6h-6z", user: "M20 21a8 8 0 0 0-16 0M12 13a4 4 0 1 0 0-8 4 4 0 0 0 0 8Z", calendar: "M5 4v3M19 4v3M4 9h16M5 6h14a1 1 0 0 1 1 1v13H4V7a1 1 0 0 1 1-1Z", message: "M20 11.5a7.5 7.5 0 0 1-8 7.5 8.6 8.6 0 0 1-3-.5L4 20l1.5-4A7.2 7.2 0 0 1 4.5 12 7.5 7.5 0 0 1 12 4.5a7.5 7.5 0 0 1 8 7Z", chart: "M4 19V5M4 19h16M8 16v-5M12 16V7M16 16v-9", star: "m12 3 2.8 5.7 6.2.9-4.5 4.4 1.1 6.2-5.6-3-5.6 3 1.1-6.2L3 9.6l6.2-.9L12 3", settings: "M9.8 3.7 10.4 2h3.2l.6 1.7 1.5.9 1.8-.3 1.6 2.8-1.2 1.3v1.8l1.2 1.3-1.6 2.8-1.8-.3-1.5.9-.6 1.7h-3.2l-.6-1.7-1.5-.9-1.8.3-1.6-2.8 1.2-1.3V8.4L4.9 7.1l1.6-2.8 1.8.3 1.5-.9ZM12 15.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7Z", bell: "M18 9a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9ZM10 21h4", heart: "m12 20-1.4-1.3C5.6 14.2 3 11.8 3 8.8A4.8 4.8 0 0 1 7.8 4c1.6 0 3.2.8 4.2 2.1C13 4.8 14.6 4 16.2 4A4.8 4.8 0 0 1 21 8.8c0 3-2.6 5.4-7.6 9.9L12 20Z" };
function Icon({ name }: { name: string }) { return <svg viewBox="0 0 24 24" aria-hidden="true"><path d={pathData[name] ?? pathData.grid} /></svg>; }

export function DashboardSidebar() {
  const pathname = usePathname(); const router = useRouter(); const { user, role, authLoading } = useAuth(); const [dialog, setDialog] = useState<"settings" | "help" | null>(null);
  useEffect(() => { if (!authLoading && (!user || role !== "tutor")) router.replace(user ? "/" : "/auth"); }, [authLoading, role, router, user]);
  useEffect(() => { const onKey = (e: KeyboardEvent) => e.key === "Escape" && setDialog(null); window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, []);
  return <><aside className="dashboard-sidebar" aria-label="Tutor dashboard navigation"><div className="dashboard-sidebar__brand"><span className="dashboard-brand-mark">T</span><span>TutorFinder</span></div><nav className="dashboard-sidebar__nav">{items.map(([href, label, icon]) => <Link className={pathname === href ? "is-active" : ""} href={href} key={label}><Icon name={icon} />{label}{label === "Messages" && <span className="dashboard-nav-badge">5</span>}</Link>)}<button className="dashboard-sidebar__nav-button" onClick={() => setDialog("settings")}><Icon name="settings" />Settings</button></nav><button className="dashboard-sidebar__help" onClick={() => setDialog("help")}><span>?</span>Help Center</button></aside>{dialog && <UtilityDialog kind={dialog} onClose={() => setDialog(null)} />}</>;
}

export function DashboardHeaderActions() {
  const { logout } = useAuth(); const router = useRouter(); const [open, setOpen] = useState<"profile" | "notifications" | null>(null); const [settingsOpen, setSettingsOpen] = useState(false); const [notificationCount, setNotificationCount] = useState(3);
  useEffect(() => { const close = () => setOpen(null); document.addEventListener("click", close); return () => document.removeEventListener("click", close); }, []);
  const signOut = () => { void logout(); router.push("/"); };
  return <><div className="dashboard-header__actions"><div className="dashboard-control-wrap"><button className="dashboard-icon-button" aria-label={`Notifications${notificationCount ? `, ${notificationCount} unread` : ""}`} aria-expanded={open === "notifications"} onClick={(e) => { e.stopPropagation(); setOpen(open === "notifications" ? null : "notifications"); }}><span className="dashboard-notification-dot" /><Icon name="bell" />{notificationCount > 0 && <span className="dashboard-notification-count">{notificationCount}</span>}</button>{open === "notifications" && <div className="dashboard-dropdown dashboard-notifications" onClick={(e) => e.stopPropagation()}><div className="dashboard-dropdown__heading"><strong>Notifications</strong><button onClick={() => setNotificationCount(0)}>Mark all as read</button></div>{[["New message from Sarah", "Your session follow-up is ready.", "8 min ago", "message"], ["New booking request", "David requested a Mathematics session.", "1 hour ago", "calendar"], ["Your profile was saved", "A learner saved your profile.", "Yesterday", "heart"]].map(([title, copy, time, icon]) => <div className="dashboard-notification" key={title}><span><Icon name={icon} /></span><div><strong>{title}</strong><p>{copy}</p><small>{time}</small></div><i /></div>)}</div>}</div><div className="dashboard-control-wrap"><button className="dashboard-avatar" aria-label="Open profile menu" aria-expanded={open === "profile"} onClick={(e) => { e.stopPropagation(); setOpen(open === "profile" ? null : "profile"); }}>AJ</button>{open === "profile" && <div className="dashboard-dropdown dashboard-profile-menu" onClick={(e) => e.stopPropagation()}><Link href="/dashboard/profile"><Icon name="user" />Profile</Link><button onClick={() => setSettingsOpen(true)}><Icon name="settings" />Settings</button><button onClick={signOut}><span aria-hidden="true">↪</span>Log out</button></div>}</div></div>{settingsOpen && <UtilityDialog kind="settings" onClose={() => setSettingsOpen(false)} />}</>;
}

function UtilityDialog({ kind, onClose }: { kind: "settings" | "help"; onClose: () => void }) { return <div className="dashboard-dialog-backdrop" onClick={(e) => e.target === e.currentTarget && onClose()}><section className="dashboard-dialog" role="dialog" aria-modal="true" aria-labelledby="utility-title"><button className="dashboard-dialog__close" onClick={onClose} aria-label="Close">×</button>{kind === "settings" ? <><p className="dashboard-kicker">PREFERENCES</p><h2 id="utility-title">Settings</h2><p className="dashboard-dialog__intro">Manage your tutor workspace preferences.</p><label className="dashboard-setting"><span><strong>Booking notifications</strong><small>Get notified when students request a session.</small></span><input type="checkbox" defaultChecked /></label><label className="dashboard-setting"><span><strong>Show profile publicly</strong><small>Let learners discover your tutor profile.</small></span><input type="checkbox" defaultChecked /></label><button className="dashboard-primary-button" onClick={onClose}>Save Settings</button></> : <><p className="dashboard-kicker">SUPPORT</p><h2 id="utility-title">How can we help?</h2><p className="dashboard-dialog__intro">Our support team can help with bookings, your profile, and anything else you need to teach with confidence.</p><p className="dashboard-support-email">Support: <a href="mailto:hello@tutorfinder.example">hello@tutorfinder.example</a></p><a className="dashboard-primary-button" href="mailto:hello@tutorfinder.example">Contact Support</a></>}</section></div>; }
export function DashboardChrome({ children, title, subtitle }: { children: ReactNode; title: string; subtitle?: string }) { return <div className="dashboard-page"><DashboardSidebar /><main className="dashboard-main"><header className="dashboard-header dashboard-reveal"><div><p className="dashboard-kicker">TUTOR WORKSPACE</p><h1>{title}</h1>{subtitle && <p>{subtitle}</p>}</div><DashboardHeaderActions /></header>{children}</main></div>; }
