"use client";

import { useState } from "react";
import { DashboardChrome } from "./DashboardControls";

const bookingData = [{ name: "Maya Chen", subject: "Algebra", time: "Today · 4:00 PM", avatar: "MC" }, { name: "Oliver Grant", subject: "Calculus", time: "Tomorrow · 10:30 AM", avatar: "OG" }];
const conversations = [{ name: "Sofia Patel", avatar: "SP", copy: "Thanks for the helpful session!", time: "10:42 AM", messages: ["Hi Alex, I really enjoyed our session today.", "Thanks for the helpful session!", "You’re welcome — see you Thursday!"] }, { name: "Maya Chen", avatar: "MC", copy: "Could we move our lesson to 5pm?", time: "Yesterday", messages: ["Could we move our lesson to 5pm?", "5pm works perfectly for me."] }, { name: "Oliver Grant", avatar: "OG", copy: "Looking forward to our next class.", time: "Aug 25", messages: ["Looking forward to our next class."] }];

export function ProfilePage() {
  const [photo, setPhoto] = useState<string | null>(null); const [saved, setSaved] = useState(false);
  return <DashboardChrome title="Your profile" subtitle="Keep your profile current so the right learners can find you."><form className="dashboard-inner-grid" onSubmit={(e) => { e.preventDefault(); setSaved(true); }}><section className="dashboard-card dashboard-form-card"><div className="dashboard-card-heading"><div><h2>Profile details</h2><p>This information is shown to learners.</p></div></div><div className="dashboard-profile-photo"><div className="dashboard-large-avatar" style={photo ? { backgroundImage: `url(${photo})` } : undefined}>{!photo && "AJ"}</div><div><strong>Profile photo</strong><p>Use a clear, friendly photo.</p><label className="dashboard-outline-button">{photo ? "Change photo" : "Upload photo"}<input type="file" accept="image/*" onChange={(e) => { const file = e.target.files?.[0]; if (file) setPhoto(URL.createObjectURL(file)); }} /></label></div></div><div className="dashboard-form-grid"><label>Full name<input defaultValue="Alex Johnson" /></label><label>Location<input defaultValue="Remote · Worldwide" /></label><label>Hourly rate<input defaultValue="$45" type="number" /></label><label>Subjects / expertise<input defaultValue="Mathematics, Algebra, Physics" /></label></div><label>Bio<textarea defaultValue="Patient and practical tutor helping learners feel confident with challenging concepts." rows={5} /></label><div className="dashboard-form-actions"><button className="dashboard-primary-button" type="submit">{saved ? "Changes saved" : "Save Changes"}</button></div></section><aside className="dashboard-card dashboard-form-card"><h2>Education</h2><p className="dashboard-form-muted">Add your background and qualifications.</p><label>Institution<input defaultValue="University of Toronto" /></label><label>Degree<input defaultValue="BSc Mathematics" /></label><label>Availability<input defaultValue="Weekdays · 3–8 PM" /></label><button className="dashboard-secondary-button" type="button">+ Add education</button></aside></form></DashboardChrome>;
}

export function BookingsPage() { const [tab, setTab] = useState<"Pending" | "Upcoming" | "Past">("Pending"); const [handled, setHandled] = useState<string[]>([]); const rows = tab === "Pending" ? bookingData : bookingData.map((x) => ({ ...x, time: tab === "Upcoming" ? "Thu · 3:30 PM" : "Aug 22 · Completed" })); return <DashboardChrome title="Bookings" subtitle="Manage requests and keep your teaching schedule moving."><section className="dashboard-card dashboard-inner-card"><div className="dashboard-card-heading"><div><h2>All bookings</h2><p>Review your sessions by status.</p></div></div><div className="dashboard-tabs">{(["Pending", "Upcoming", "Past"] as const).map((item) => <button className={tab === item ? "is-active" : ""} onClick={() => setTab(item)} key={item}>{item}</button>)}</div><div className="dashboard-booking-list">{rows.map((booking) => <div className="dashboard-booking-row" key={booking.name}><span className="dashboard-person-avatar">{booking.avatar}</span><div><strong>{booking.name}</strong><p>{booking.subject} · {booking.time}</p></div>{tab === "Pending" && !handled.includes(booking.name) ? <div className="dashboard-booking-actions"><button className="dashboard-action-accept" onClick={() => setHandled([...handled, booking.name])}>Accept</button><button className="dashboard-action-decline" aria-label={`Decline ${booking.name}`} onClick={() => setHandled([...handled, booking.name])}>×</button></div> : <span className="dashboard-booking-status">{handled.includes(booking.name) ? "Handled" : tab === "Past" ? "Completed" : "Confirmed"}</span>}</div>)}</div></section></DashboardChrome>; }

export function MessagesPage() { const [selected, setSelected] = useState(0); const [draft, setDraft] = useState(""); const [sent, setSent] = useState<string[]>([]); const conversation = conversations[selected]; return <DashboardChrome title="Messages" subtitle="Stay connected with your students."><section className="dashboard-card dashboard-messages-page"><div className="dashboard-conversation-list">{conversations.map((item, index) => <button className={selected === index ? "is-active" : ""} onClick={() => setSelected(index)} key={item.name}><span className="dashboard-person-avatar">{item.avatar}</span><span><strong>{item.name}</strong><small>{item.copy}</small></span><time>{item.time}</time>{index < 2 && <i />}</button>)}</div><div className="dashboard-chat"><div className="dashboard-chat__header"><span className="dashboard-person-avatar">{conversation.avatar}</span><div><strong>{conversation.name}</strong><small>Usually replies in a few minutes</small></div></div><div className="dashboard-chat__body">{conversation.messages.map((message, index) => <p className={index % 2 ? "is-own" : ""} key={`${message}-${index}`}>{message}</p>)}{sent.map((message) => <p className="is-own" key={message}>{message}</p>)}</div><form className="dashboard-chat__input" onSubmit={(e) => { e.preventDefault(); if (draft.trim()) { setSent([...sent, draft.trim()]); setDraft(""); } }}><input value={draft} onChange={(e) => setDraft(e.target.value)} placeholder="Write a message..." aria-label="Message" /><button className="dashboard-primary-button">Send</button></form></div></section></DashboardChrome>; }

export function EarningsPage() { const [range, setRange] = useState("30D"); return <DashboardChrome title="Earnings" subtitle="A clear view of your tutoring income."><section className="dashboard-stats"><article className="dashboard-card dashboard-stat"><p>Total Earnings</p><strong>$4,860</strong><span className="dashboard-stat__change">+18.4%</span></article><article className="dashboard-card dashboard-stat"><p>This Month</p><strong>$1,240</strong><span className="dashboard-stat__change">+8.2%</span></article><article className="dashboard-card dashboard-stat"><p>Pending Earnings</p><strong>$320</strong><span className="dashboard-stat__note">2 sessions</span></article><article className="dashboard-card dashboard-stat"><p>Withdrawn</p><strong>$4,540</strong><span className="dashboard-stat__note">Last Aug 20</span></article></section><section className="dashboard-card dashboard-inner-card dashboard-earnings-chart"><div className="dashboard-card-heading"><div><h2>Earnings trend</h2><p>Your earnings over time</p></div><div className="dashboard-range">{["7D", "30D", "90D", "1Y"].map((item) => <button className={range === item ? "is-active" : ""} onClick={() => setRange(item)} key={item}>{item}</button>)}</div></div><svg viewBox="0 0 100 70" preserveAspectRatio="none" role="img" aria-label={`Earnings trend for ${range}`}><polyline className="dashboard-line-path" points="0,58 12,50 25,54 38,35 50,42 62,22 75,30 87,12 100,20" fill="none" /></svg></section></DashboardChrome>; }

export function ReviewsPage() { return <DashboardChrome title="Reviews" subtitle="See what learners appreciate about your teaching."><section className="dashboard-review-summary dashboard-card"><div><span>Average Rating</span><strong>4.9 <small>★★★★★</small></strong></div><div><span>Total Reviews</span><strong>128</strong></div><div><span>Recommend</span><strong>98%</strong></div></section><section className="dashboard-review-grid">{[["Sofia Patel", "SP", "5.0", "Alex made every step feel simple and approachable. I left the session feeling much more confident.", "Aug 24, 2026"], ["Maya Chen", "MC", "5.0", "Excellent explanations and really thoughtful examples. The session was exactly what I needed.", "Aug 18, 2026"], ["Oliver Grant", "OG", "4.8", "Patient, organized, and always prepared. I’m looking forward to our next class.", "Aug 11, 2026"]].map(([name, avatar, rating, text, date]) => <article className="dashboard-card dashboard-review-card" key={name}><div><span className="dashboard-person-avatar">{avatar}</span><div><strong>{name}</strong><small>{date}</small></div><b>★★★★★</b></div><p>{text}</p><small>{rating} rating</small></article>)}</section></DashboardChrome>; }
