"use client";

import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import { useFindTutorsViewModel } from "./useFindTutorsViewModel";
import { experienceOptions, priceBounds, regionOptions, subjectOptions, type FindTutor } from "./FindTutorsModel";
import "./FindTutorsView.css";

const FilterIcon = () => <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 6h16M4 12h16M4 18h16" /><circle cx="8" cy="6" r="2" /><circle cx="15" cy="12" r="2" /><circle cx="10" cy="18" r="2" /></svg>;
const LocationIcon = () => <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z" /><circle cx="12" cy="10" r="2.5" /></svg>;
const StarIcon = () => <svg viewBox="0 0 24 24" aria-hidden="true"><path d="m12 3 2.8 5.7 6.2.9-4.5 4.4 1.1 6.2-5.6-3-5.6 3 1.1-6.2L3 9.6l6.2-.9L12 3Z" /></svg>;
const CrownIcon = () => <svg viewBox="0 0 24 24" aria-hidden="true"><path d="m4 7 4 4 4-6 4 6 4-4-2 11H6L4 7Z" /><path d="M6 21h12" /></svg>;
const CheckIcon = () => <svg viewBox="0 0 24 24" aria-hidden="true"><path d="m5 12 4 4L19 6" /><circle cx="12" cy="12" r="9" /></svg>;
const PersonIcon = () => <svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="8" r="3.5" /><path d="M5 21a7 7 0 0 1 14 0" /></svg>;
const GridIcon = () => <svg viewBox="0 0 24 24" aria-hidden="true"><rect x="4" y="4" width="6" height="6" rx="1" /><rect x="14" y="4" width="6" height="6" rx="1" /><rect x="4" y="14" width="6" height="6" rx="1" /><rect x="14" y="14" width="6" height="6" rx="1" /></svg>;
const ListIcon = () => <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M9 6h11M9 12h11M9 18h11" /><circle cx="4.5" cy="6" r="1" /><circle cx="4.5" cy="12" r="1" /><circle cx="4.5" cy="18" r="1" /></svg>;

function TutorCard({ tutor }: { tutor: FindTutor }) {
  const [hireOpen, setHireOpen] = useState(false); const initials = tutor.name.split(" ").map((part) => part[0]).join(""); const contactName = tutor.name.toLowerCase().replace(/[^a-z0-9]+/g, ".").replace(/^\.|\.$/g, ""); const email = `${contactName}@tutorfinder.example`; const whatsapp = `+1 (555) 010-${tutor.id.padStart(4, "0")}`;
  return <article className="find-tutor-card"><div className="find-tutor-card__top"><span className={`find-tutor-card__badge find-tutor-card__badge--${tutor.badge === "Top Rated" ? "top" : "recommended"}`}>{tutor.badge === "Top Rated" ? <CrownIcon /> : <CheckIcon />}{tutor.badge}</span><div className="find-tutor-card__avatar-wrap"><span className="find-tutor-card__avatar" aria-label={`${tutor.name} profile`}>{initials}</span><span className="find-tutor-card__online" aria-label="Available" /></div></div><div className="find-tutor-card__rating"><StarIcon /><strong>{tutor.rating.toFixed(1)}</strong><span>({20 + Number(tutor.id) * 7})</span></div><h3>{tutor.name}</h3><p className="find-tutor-card__subject">{tutor.subject} Tutor</p><p className="find-tutor-card__bio">{tutor.bio}</p><div className="find-tutor-card__tags">{tutor.tags.map((tag) => <span key={tag}>{tag}</span>)}<span>+2</span></div><div className="find-tutor-card__footer"><strong>${tutor.price}<small> / hour</small></strong><div><button type="button" className="find-tutor-card__hire" onClick={() => setHireOpen(true)}><PersonIcon />Hire this tutor</button><Link href={`/tutor/${tutor.id}`} className="find-tutor-card__details">View details</Link></div></div>{hireOpen && <div className="hire-tutor-modal" role="dialog" aria-modal="true" aria-labelledby={`hire-title-${tutor.id}`} onClick={(event) => event.target === event.currentTarget && setHireOpen(false)}><section className="hire-tutor-modal__card"><button type="button" className="hire-tutor-modal__close" aria-label="Close contact details" onClick={() => setHireOpen(false)}>×</button><div className="find-tutor-card__avatar">{initials}</div><h2 id={`hire-title-${tutor.id}`}>Contact {tutor.name}</h2><p className="hire-tutor-modal__subject">{tutor.subject} Tutor</p><dl><div><dt>Email</dt><dd><a href={`mailto:${email}`}>{email}</a></dd></div><div><dt>WhatsApp</dt><dd><a href={`https://wa.me/${whatsapp.replace(/\D/g, "")}`} target="_blank" rel="noreferrer">{whatsapp}</a></dd></div></dl><a className="hire-tutor-modal__message" href={`mailto:${email}?subject=${encodeURIComponent(`TutorFinder message for ${tutor.name}`)}`}>Message</a></section></div>}</article>;
}

function FilterSidebar({ vm, mobile = false }: { vm: ReturnType<typeof useFindTutorsViewModel>; mobile?: boolean }) {
  return <aside className={`find-filters${mobile ? " find-filters--mobile" : ""}`} aria-label="Tutor filters"><div className="find-filters__heading"><h2><FilterIcon />Filter Tutors</h2><button type="button" onClick={vm.resetFilters}>Reset all</button></div><fieldset><legend>Subjects <span>⌃</span></legend>{subjectOptions.map((subject) => <label key={subject}><input type="checkbox" checked={subject === "All Subjects" ? vm.draftFilters.subjects.length === 0 : vm.draftFilters.subjects.includes(subject)} onChange={() => vm.toggleSubject(subject)} /><span className="find-checkbox" />{subject}</label>)}<button type="button" className="find-filters__more">+ &nbsp;Show more</button></fieldset><fieldset><legend>Region <span>⌃</span></legend><label className="find-select"><LocationIcon /><select value={vm.draftFilters.region} onChange={(event) => vm.setDraftFilter("region", event.target.value)}>{regionOptions.map((region) => <option key={region}>{region}</option>)}</select><span>⌄</span></label></fieldset><fieldset><legend>Experience <span>⌃</span></legend>{experienceOptions.map((experience) => <label key={experience}><input type="checkbox" checked={vm.draftFilters.experience === experience} onChange={() => vm.setDraftFilter("experience", experience)} /><span className="find-checkbox" />{experience}</label>)}</fieldset><fieldset className="find-price"><legend>Price per hour <span>⌃</span></legend><div className="find-range"><input type="range" min={priceBounds.min} max={priceBounds.max} value={vm.draftFilters.minPrice} onChange={(event) => vm.setDraftFilter("minPrice", Math.min(Number(event.target.value), vm.draftFilters.maxPrice - 1))} /><input type="range" min={priceBounds.min} max={priceBounds.max} value={vm.draftFilters.maxPrice} onChange={(event) => vm.setDraftFilter("maxPrice", Math.max(Number(event.target.value), vm.draftFilters.minPrice + 1))} /></div><div className="find-price__labels"><span>${vm.draftFilters.minPrice}</span><span>${vm.draftFilters.maxPrice}+</span></div></fieldset><button type="button" className="find-filters__apply" onClick={vm.applyFilters}>Apply Filters</button><button type="button" className="find-filters__clear" onClick={vm.resetFilters}>Clear All</button>{mobile && <button type="button" className="find-filters__close" onClick={() => vm.setMobileFiltersOpen(false)}>Close</button>}</aside>;
}

export default function FindTutorsView() {
  const vm = useFindTutorsViewModel();
  return <main className="find-tutors-page"><header className="find-tutors-hero"><div><p className="find-tutors-eyebrow">Find the perfect tutor for your learning journey</p><h1>Find Tutors</h1><p>Learn from experienced tutors who make every lesson feel personal.</p></div><div className="find-tutors-hero__visual"><div className="find-tutors-hero__blob find-tutors-hero__blob--one" /><div className="find-tutors-hero__blob find-tutors-hero__blob--two" /><Image src="/images/find-tutors-illustration.png" alt="Tutor helping a learner online" width={600} height={400} priority /><div className="find-tutors-hero__count"><strong>{vm.filteredTutors.length} Tutors found</strong><span>Showing results based on your filters</span></div></div></header><div className="find-tutors-layout"><FilterSidebar vm={vm} /><div className="find-results"><div className="find-results__toolbar"><button type="button" className="find-mobile-filter-button" onClick={() => vm.setMobileFiltersOpen(true)}><FilterIcon />Filters</button><label className="find-sort">Sort by:<select value={vm.sortBy} onChange={(event) => vm.setSortBy(event.target.value as typeof vm.sortBy)}><option>Most Relevant</option><option>Highest Rated</option><option>Lowest Price</option></select><span>⌄</span></label><div className="find-view-toggle"><button type="button" className={vm.viewMode === "grid" ? "is-active" : ""} onClick={() => vm.setViewMode("grid")}><GridIcon />Grid</button><button type="button" className={vm.viewMode === "list" ? "is-active" : ""} onClick={() => vm.setViewMode("list")}><ListIcon />List</button></div></div>{vm.loading ? <div className="find-state">Loading tutors…</div> : vm.error ? <div className="find-state">{vm.error}</div> : vm.visibleTutors.length === 0 ? <div className="find-state"><h2>No tutors found</h2><p>Try adjusting your filters or clearing some selections.</p><button type="button" onClick={vm.resetFilters}>Clear Filters</button></div> : <div className={`find-tutor-grid find-tutor-grid--${vm.viewMode}`}>{vm.visibleTutors.map((tutor) => <TutorCard key={tutor.id} tutor={tutor} />)}</div>}<nav className="find-pagination" aria-label="Tutor results pages"><button type="button" onClick={() => vm.setPage(vm.currentPage - 1)} disabled={vm.currentPage === 1} aria-label="Previous page">‹</button>{Array.from({ length: vm.pageCount }, (_, index) => index + 1).slice(0, 4).map((page) => <button key={page} type="button" className={page === vm.currentPage ? "is-active" : ""} onClick={() => vm.setPage(page)}>{page}</button>)}{vm.pageCount > 4 && <span>…</span>}<button type="button" onClick={() => vm.setPage(vm.currentPage + 1)} disabled={vm.currentPage === vm.pageCount} aria-label="Next page">›</button></nav></div></div>{vm.mobileFiltersOpen && <div className="find-mobile-filter-overlay"><FilterSidebar vm={vm} mobile /></div>}</main>;
}
